### ISSUE TITLE
Import existing notebook images input into ODH [Admin]

### ISSUE THREAD

**Issue by pacospace** [open-services-group/byon#1]
As Operator/Admin,

I have existing images I want to import in ODH. The system must enable users to bring in/import notebook images via the UI (eg. users should not have to edit config files such as YAML files). After import, the images should be available for selection in the UI like out-of-the-box images. 

Note: by default, imported images would be available for all cluster users.

Related-To: https://issues.redhat.com/browse/RHODS-2211 req 1

**Comment by pacospace** [comment]
Questions:
1. Are the images supposed to be spawnable from JH?

**Comment by pacospace** [comment]
- [ ] have a validation step in the pipeline with specific case for admin.

**Comment by tumido** [comment]
Questions:
1. To bring in/import notebook images means what exactly on the input? URL to an image registry? Do we need to also handle credentials to private registries?
2. Where is the user (admin) expected to enter this input into? JupyterHub Spawner UI? Meteor Shower? This also impacts where the UI feedback is reported..

**Comment by tumido** [comment]
Based on [s2i-minimal-notebook](https://github.com/thoth-station/s2i-minimal-notebook), each image should include following prerequisites:

### Python packages
Based on `requirements.in` and `Pipfile` at:
https://github.com/thoth-station/s2i-minimal-notebook/tree/master/overlays/f34-python39
https://github.com/thoth-station/s2i-minimal-notebook/tree/master/overlays/python36
https://github.com/thoth-station/s2i-minimal-notebook/tree/master/overlays/python38

| Package name | Note |
| --- | --- |
| `notebook` | Provides the classic notebook interface. Either this or `jupyterlab` has to be present |
| `jupyterhub` | Provides Spawned. Also transitive dependency from [jupyterhub-singleuser-profiles](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles)  |
| `jupyterlab` | Provides the JupyterLab UI interface. Either this or `jupyterhub` has to be present |
| `jupyterlab-requirements` | Requires `jupyterlab`, it is NOT present in Python 3.6 overlay |
| `jupyter_kernel_gateway` | This was probably never used. |
| `jupyter-nbrequirements` | Extension to JupyterLab |
| `supervisor` | This was probably used only when WEBDAV is enabled, which I never saw... |
| `jupyterlab-git` | Extension enabling git. Requires `git` distribution package. |
| `jupyterlab-spellchecker` | Extension. This is NOT present in Python 3.6 overlay |

### System packages

- Python
- Git
- Openshift Client

### Configuration
- [Jupyter classic UI config](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/jupyter_notebook_config.py) if `notebook` is installed and used
- [JupyterLab configuration](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/jupyter_server_config.py) if `jupyterlab` is installed and used
- Local kubernetes/OpenShift [credentials config](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/setup-environ.sh) for `oc`
- Entrypoint starting either `jupyter lab` or `jupyter notebook` however this might be wrapped in many nested scripts ([`.s2i/bin/run`](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/.s2i/bin/run) -> [`builder/run`](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/builder/run) -> [`start-notebook.sh`](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-notebook.sh) -> [`start.sh`](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start.sh))

### Omitted scenarios

I'm ignoring following scenarios and usecases, because they are either not used at all or they don't cover the base functionality we'd like to ensure in our "pre-flight check":
- [Volume](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/setup-volume.sh) syncing
- Start as single user profiles for JupyterHub [1](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-singleuser.sh) [2](https://github.com/thoth-station/s2i-minimal-notebook/blob/e78213c5305f540ef8c18eff1eea3a6b3f89e181/start-notebook.sh#L52)
- Start as [webdav](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-webdav.sh) via Supervisord (with following [config](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/httpd-webdav.conf)) 
- Start as a gateway [1](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-kernelgateway.sh) [1](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-gateway.sh)
- Start as a [dusk scheduler](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-daskscheduler.sh)
- Start as a [dusk worker](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-daskworker.sh)

**Comment by pacospace** [comment]
@tumido 

jupyter-nbrequirements | Extension to JupyterLab. Requires jupyterlab.
-- | --

is a classical jupyter notebook extension actually, not jupyterlab one: https://github.com/thoth-station/jupyter-nbrequirements. It is not maintained

**Comment by tumido** [comment]
Important note:

The comment above is focusing solely on the current JupyterHub architecture in RHODS and ODH. Many of those requirements are not hard requirements for Kubeflow Notebook Controller.

**Comment by pacospace** [comment]
Related-To: https://github.com/open-services-group/byon/issues/16

**Comment by tumido** [comment]
Summary of 2022-01-19 WG mtg for BYON:
- We're not yet decided if we are targetting KFNBC or JpyterHub spawner as the backend
- The input happens in RHODS UI interface which a separate UI from the JupyterHub spawner, it is a intergated UI admin panel for the whole RHODS
- Validation is required since we can't be delivering image that is not spawneble (no matter what backend)
- Output ImageStream stays the same as if were targeting JupyterHub spawner
- For MVP we should target a very minimal validation, until the backend (KFNBC or JH Spawner) is decided
- For MVP we're targeting public images only, we don't need to handle container repository credentials at this point

**Comment by tumido** [comment]
This issue mostly describes the MVP as a whole, let's remove it from the task board and turn this into an epic. Carving out the notebook requirements into a separate issue.
