### ISSUE TITLE
Periodic polling of container images

### ISSUE THREAD

**Issue by tumido** [open-services-group/byon#17]
Investigate how to manage imagestream updates. This issue is looking for answers/analysis on:

- If an image in external registry is update, how is this change propagated to `Imagestream` in Openshift
  - Scheduled import via [`importPolicy.scheduled`](https://docs.openshift.com/container-platform/4.9/openshift_images/image-streams-manage.html#images-imagestream-import_image-streams-managing) on `Imagestream`
  - Investigate what happened with `referencePolicy` in OCP 4.x, since it's missing from the docs, but present in the resource manifests ([OCP 3.x docs here](https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#reference-policy))
- How/if we can trigger a validation pipeline on image update
  - Investigate if Openshift can trigger pipelinerun from native [image trigger](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html-single/images/index#images-triggering-updates-imagestream-changes-kubernetes-about_triggering-updates-on-imagestream-changes)
  - Investigate if there are Tekton Triggers for this
- Also Image pull policy plays their role here https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy

Based on my initial screening it seems there's no way to gate when image stream tag import if set to scheduled. Also it's unsure when the cache is cleaned or accessed (is this per node?) and how an image is cached. Investigate what happens when pods are started: if the image is pulled from a remote repository or mirrored to internal container registry on the first start and pulled from there. What happens when pod is scheduled to a different node (again pulling from internal/external registry?) Experiments needed. It effects when we get the updated image and if we know about it or user is served a newer version withouth admin/validation pipeline noticing first.

Besides scheduled import described above, there's no common reactive facility to initiate/trigger notification from remote registries - webhooks etc, this is remote repository specific and must be set on the remote repository side.

**Comment by mimotej** [comment]
So far I have conducted some experiments and I have the following information:
1. `importPolicy.scheduled` on `Imagestream` causes that OCP to periodically check for changes on the image (meaning it checks if digest of an image has changed). This can be useful for automatic updates of images, but it does not generate any event, so it might be harder to detect.
2. `referencePolicy` works in the same way in OCP 4.x as in OCP 3.x - not sure why it is not mentioned in the docs, but there doesn't seem to be any change. One bit that is also mentioned in the docs is that when using `referencePolicy.type Local` we have to set `importPolicy.insecure` otherwise the image will not be pulled. When using `referencePolicy.type Source` this is not the case, and you don't have to set `importPolicy.insecure`. One interesting bit, it seems that even in case of `referencePolicy.type Source` `ImageStream` stores image to internal registry, but only instructs client to pull from external when possible (it also points to manifest SHA address not tag). In my test I have created `ImageStream` with `referencePolicy.type Source` and even though I deleted image from external image registry it was still able to pull image which didn't exist.
3. Another important part is pull policy, which is defined in pod creation. In this case, `imagePullPolicy` can have three values `IfNotPresent`, `Always`, `Never`, where `Never` isn't useful for us, because it only starts container when the image is pre-cached on the node. `ifNotPresent` checks if an image exists with same name and tag (it doesn't consider differences in digests) and if it is available it creates a container, otherwise it pulls an image. `Always` also checks if image is pre-cached, but it also checks digests and if they are not the same (for example tag didn't change, but there were some security patches), it pulls new image.
4. Triggering pipelines is another problem we need to resolve first I have found examples from Andrew block [how to trigger pipelines when image changes](https://github.com/sabre1041/image-trigger-tekton), but as I mentioned earlier `ImageStream` does not generate event upon image change, so this option is not usable in our case. 
Combing policies 1-3, seems to result in predictable behavior which seems to follow what is written in docs or what I have written above.
There are still some scenarios which need further testing, once I try other possible scenarios I will extend this comment on these notes as well.

**Comment by tumido** [comment]
Great research! Thank you!

> 1. ...but it does not generate any event, so it might be harder to detect.

I think it won't be a problem. It generates event/action via additional kubernetes resources like the creation of `Image` resource and `ImageStreamTag` resource update. That should do the trick.

> 2. ...i n my test I have created `ImageStream` with `referencePolicy.type Source` and even though I deleted image from external image registry it was still able to pull image which didn't exist.

I think this is the behavior we want to achieve, correct? Cache the image in local registry and reuse it from there, without ever pulling from a remote for pod spawns. Good.

> 3. ... `ifNotPresent` checks if an image exists with same name and tag (it doesn't consider differences in digests) and if it is available it creates a container, otherwise it pulls an image.

What does it mean if the image is available? In the internal registry or in node cache? When it is not available where does it pull from (internal registry or remote location)? Is this affected by `referencePolicy.type`? 

> 4. ... [how to trigger pipelines when image changes](https://github.com/sabre1041/image-trigger-tekton), but as I mentioned earlier ImageStream does not generate event upon image change

Yes, something like Andrew's demo will solve it for us. Again, we don't need `Events`, Knative can trigger on API actions/changes, that's all we need. I was eyeballing KNative for this prior to knowing about Andrew's demo. I think we're heading in the right direction here.

**Comment by tumido** [comment]
In my test I've used an image stream with `referencePolicy.type: Local` and `importPolicy.scheduled: true`:

1. Spawn a pod in JupyterHub - it pulls the image from internal registry
2. Shut down the pod
3. Spawn a new pod in JupyterHub - it pulls the image from node cache
4. Shut down the pod 
5. Updating image tag in remote container image repository - After a while it triggers a scheduled import
6. Spawning a new pod in JupyterHub - it pulls the image from internal registry
7. Shut down the pod
8. Delete the tag in remote container image repository - After a while the Image Stream reports import error 
9. Spawning a new pod in JupyterHub  - it pulls the image from node cache
10. Shut down the pod
11. Mark the node of previous pods unschedulable
12. Spawn a pod in JupyterHub - it pulls the image from internal registry

I think this solution works, wdyt @mimotej ?

**Comment by mimotej** [comment]
Yes, I think this configuration will give us most consistent results out of all options :+1: .

**Comment by tumido** [comment]
Good, then the proposed design will be:

```mermaid
flowchart TD
A[Image updated in remote container repository]
B[ImageStreamTag updated in internal container repository]
C[Knative eventing triggers a PipelineRun]
D[Mark phase 'Updating/Validating' and hides it from UI]
E[Run validation checks]
F{Did checks pass?}
G[Mark phase 'Success' and show in UI]
H[Mark phase 'Failed']
A --> B --> C --> D --> F
C --> E --> F
F -- Yes --> G
F -- No --> H
```

This approach has few drawbacks.
1. The image stream disappears without explanation from the user facing UI (we probably need to show it as "disabled" to lower user confusion)
2. There's a small window between validation pipeline marking the imagestream as unavailable due to running validation and the actual imagestream update potentially allowing users to click the image in Spawner UI while the image is already updated and was not yet validated.
3.  Automatic update and validation may result in image failing the validation. In such case ImageStreams don't support any rollback options. We would need to workaround that (possibly adding a backup tag pointing to previously resolved image, but I'm not yet sure if that's possible)

Local resolution has 1 significant positive effect:
- Image is available in internal container registry even if it disappears from the source registry = Stable behavior.

**Comment by tumido** [comment]
Decision. This is postponed/deprioritized due to the necessity to introduce a KNative dependency. Revisit post-MVP.

**Comment by codificat** [comment]
going to
/lifecycle frozen
this to prevent auto-closure for the time being

**Comment by schwesig** [comment]
mentioned to @codificat

**Comment by codificat** [comment]
As BYON evolved into Custom Notebook Images, which currently use an operator to manage the imagestreams and pipeline runs, I believe this is not relevant anymore.

/close

Having said that, it's worth exploring what [meteor-operator](https://github.com/thoth-station/meteor-operator) could do to keep custom images current. But that will be handled in its own repo and issue
